const citiesByProvince: { [key: string]: string[] } = {
  Aceh: [
    "Banda Aceh",
    "Langsa",
    "Lhokseumawe",
    "Meulaboh",
    "Sabang",
    "Subulussalam",
  ],
  Bali: ["Denpasar"],
  Banten: ["Cilegon", "Serang", "Tangerang", "Tangerang Selatan"],
  Bengkulu: ["Bengkulu"],
  "DI Yogyakarta": ["Yogyakarta"],
  "DKI Jakarta": [
    "Jakarta Barat",
    "Jakarta Pusat",
    "Jakarta Selatan",
    "Jakarta Timur",
    "Jakarta Utara",
  ],
  Gorontalo: ["Gorontalo"],
  Jambi: ["Jambi"],
  "Jawa Barat": [
    "Bandung",
    "Bekasi",
    "Bogor",
    "Cimahi",
    "Cirebon",
    "Depok",
    "Sukabumi",
    "Tasikmalaya",
    "Banjar",
  ],
  "Jawa Tengah": [
    "Magelang",
    "Pekalongan",
    "Salatiga",
    "Semarang",
    "Surakarta",
    "Tegal",
  ],
  "Jawa Timur": [
    "Batu",
    "Blitar",
    "Kediri",
    "Madiun",
    "Malang",
    "Mojokerto",
    "Pasuruan",
    "Probolinggo",
    "Surabaya",
  ],
  "Kalimantan Barat": ["Pontianak", "Singkawang"],
  "Kalimantan Selatan": ["Banjarbaru", "Banjarmasin"],
  "Kalimantan Tengah": ["Palangka Raya"],
  "Kalimantan Timur": ["Balikpapan", "Bontang", "Samarinda"],
  "Kalimantan Utara": ["Tarakan"],
  "Kepulauan Bangka Belitung": ["Pangkal Pinang"],
  "Kepulauan Riau": ["Batam", "Tanjung Pinang"],
  Lampung: ["Bandar Lampung", "Metro"],
  Maluku: ["Ambon", "Tual"],
  "Maluku Utara": ["Ternate", "Tidore Kepulauan"],
  "Nusa Tenggara Barat": ["Bima", "Mataram"],
  "Nusa Tenggara Timur": ["Kupang"],
  Papua: ["Jayapura"],
  "Papua Barat": ["Sorong"],
  Riau: ["Dumai", "Pekanbaru"],
  "Sulawesi Barat": ["Mamuju"],
  "Sulawesi Selatan": ["Makassar", "Palopo", "Parepare"],
  "Sulawesi Tengah": ["Palu"],
  "Sulawesi Tenggara": ["Bau-Bau", "Kendari"],
  "Sulawesi Utara": ["Bitung", "Kotamobagu", "Manado", "Tomohon"],
  "Sumatera Barat": [
    "Bukittinggi",
    "Padang",
    "Padang Panjang",
    "Pariaman",
    "Payakumbuh",
    "Sawahlunto",
    "Solok",
  ],
  "Sumatera Selatan": ["Lubuklinggau", "Pagar Alam", "Palembang", "Prabumulih"],
  "Sumatera Utara": [
    "Binjai",
    "Gunungsitoli",
    "Medan",
    "Padang Sidempuan",
    "Pematangsiantar",
    "Sibolga",
    "Tanjungbalai",
    "Tebing Tinggi",
  ],
};

const districtsByCity: { [key: string]: string[] } = {
  "Banda Aceh": ["Baiturrahman", "Kuta Alam", "Meuraxa"],
  Denpasar: ["Denpasar Barat", "Denpasar Selatan", "Denpasar Timur"],
  Cilegon: ["Cibeber", "Cilegon", "Jombang"],
  // Add more cities and their respective districts here
  Serang: ["Curug", "Kasemen", "Serang", "Taktakan", "Walantaka"],
  Tangerang: [
    "Batuceper",
    "Benda",
    "Cibodas",
    "Ciledug",
    "Cipondoh",
    "Jatiuwung",
    "Karang Tengah",
    "Karawaci",
    "Larangan",
    "Neglasari",
    "Periuk",
    "Pinang",
    "Tangerang",
  ],
  "Tangerang Selatan": [
    "Ciputat",
    "Ciputat Timur",
    "Pamulang",
    "Pondok Aren",
    "Serpong",
    "Serpong Utara",
    "Setu",
  ],
  Bengkulu: [
    "Gading Cempaka",
    "Kampung Melayu",
    "Muara Bangka Hulu",
    "Ratu Agung",
    "Ratu Samban",
    "Selebar",
    "Singaran Pati",
    "Sungai Serut",
    "Teluk Segara",
  ],
  Yogyakarta: [
    "Danurejan",
    "Gedongtengen",
    "Gondokusuman",
    "Gondomanan",
    "Jetis",
    "Kotagede",
    "Kraton",
    "Mantrijeron",
    "Mergangsan",
    "Ngampilan",
    "Pakualaman",
    "Tegalrejo",
    "Umbulharjo",
    "Wirobrajan",
  ],
  "Jakarta Barat": [
    "Cengkareng",
    "Grogol Petamburan",
    "Kalideres",
    "Kebon Jeruk",
    "Kembangan",
    "Palmerah",
    "Taman Sari",
    "Tambora",
  ],
  "Jakarta Pusat": [
    "Cempaka Putih",
    "Gambir",
    "Johar Baru",
    "Kemayoran",
    "Menteng",
    "Sawah Besar",
    "Senen",
    "Tanah Abang",
  ],
  "Jakarta Selatan": [
    "Cilandak",
    "Jagakarsa",
    "Kebayoran Baru",
    "Kebayoran Lama",
    "Mampang Prapatan",
    "Pancoran",
    "Pasar Minggu",
    "Pesanggrahan",
    "Setiabudi",
    "Tebet",
  ],
  "Jakarta Timur": [
    "Cakung",
    "Cipayung",
    "Ciracas",
    "Duren Sawit",
    "Jatinegara",
    "Kramat Jati",
    "Makasar",
    "Matraman",
    "Pasar Rebo",
    "Pulo Gadung",
  ],
  "Jakarta Utara": [
    "Cilincing",
    "Kelapa Gading",
    "Koja",
    "Pademangan",
    "Penjaringan",
    "Tanjung Priok",
  ],
  Gorontalo: [
    "Dumbo Raya",
    "Dungingi",
    "Hulonthalangi",
    "Kota Barat",
    "Kota Selatan",
    "Kota Tengah",
    "Kota Timur",
    "Kota Utara",
    "Sipatana",
  ],
  Jambi: [
    "Danau Sipin",
    "Jambi Selatan",
    "Jambi Timur",
    "Jelutung",
    "Kota Baru",
    "Pasar Jambi",
    "Pelayangan",
    "Telanaipura",
  ],
  Bandung: [
    "Andir",
    "Antapani",
    "Arcamanik",
    "Astanaanyar",
    "Babakan Ciparay",
    "Bandung Kidul",
    "Bandung Kulon",
    "Bandung Wetan",
    "Batununggal",
    "Bojongloa Kaler",
    "Bojongloa Kidul",
    "Buahbatu",
    "Cibeunying Kaler",
    "Cibeunying Kidul",
    "Cibiru",
    "Cicendo",
    "Cidadap",
    "Cinambo",
    "Coblong",
    "Gedebage",
    "Kiaracondong",
    "Lengkong",
    "Mandalajati",
    "Panyileukan",
    "Rancasari",
    "Regol",
    "Sukajadi",
    "Sukasari",
    "Sumur Bandung",
    "Ujungberung",
  ],
  Bekasi: [
    "Bantar Gebang",
    "Bekasi Barat",
    "Bekasi Selatan",
    "Bekasi Timur",
    "Bekasi Utara",
    "Jatiasih",
    "Jatisampurna",
    "Medan Satria",
    "Mustika Jaya",
    "Pondok Gede",
    "Pondok Melati",
    "Rawalumbu",
  ],
  Bogor: [
    "Bogor Barat",
    "Bogor Selatan",
    "Bogor Tengah",
    "Bogor Timur",
    "Bogor Utara",
    "Tanah Sareal",
  ],
  Cimahi: ["Cimahi Selatan", "Cimahi Tengah", "Cimahi Utara"],
  Cirebon: ["Harjamukti", "Kejaksan", "Kesambi", "Lemahwungkuk", "Pekalipan"],
  Depok: [
    "Beji",
    "Bojongsari",
    "Cilodong",
    "Cimanggis",
    "Cinere",
    "Cipayung",
    "Limo",
    "Pancoran Mas",
    "Sawangan",
    "Sukmajaya",
    "Tapos",
  ],
  Sukabumi: [
    "Baros",
    "Cibeureum",
    "Cikole",
    "Citamiang",
    "Gunung Puyuh",
    "Lembursitu",
    "Warudoyong",
  ],
  Tasikmalaya: [
    "Bungursari",
    "Cibeureum",
    "Cihideung",
    "Cipedes",
    "Indihiang",
    "Kawalu",
    "Mangkubumi",
    "Purbaratu",
    "Tamansari",
    "Tawang",
  ],
  Banjar: ["Banjar", "Langensari", "Pataruman", "Purwaharja"],
  Magelang: ["Magelang Selatan", "Magelang Tengah", "Magelang Utara"],
  Pekalongan: [
    "Pekalongan Barat",
    "Pekalongan Selatan",
    "Pekalongan Timur",
    "Pekalongan Utara",
  ],
  Salatiga: ["Argomulyo", "Sidomukti", "Sidorejo", "Tingkir"],
  Semarang: [
    "Banyumanik",
    "Candisari",
    "Gajahmungkur",
    "Gayamsari",
    "Genuk",
    "Gunungpati",
    "Mijen",
    "Ngaliyan",
    "Pedurungan",
    "Semarang Barat",
    "Semarang Selatan",
    "Semarang Tengah",
    "Semarang Timur",
    "Semarang Utara",
    "Tembalang",
    "Tugu",
  ],
  Surakarta: ["Banjarsari", "Jebres", "Laweyan", "Pasar Kliwon", "Serengan"],
  Tegal: ["Margadana", "Tegal Barat", "Tegal Selatan", "Tegal Timur"],
  Batu: ["Batu", "Bumiaji", "Junrejo"],
  Blitar: ["Kepanjenkidul", "Sananwetan", "Sukorejo"],
  Kediri: ["Kediri", "Mojoroto", "Pesantren"],
  Madiun: ["Kartoharjo", "Manguharjo", "Taman"],
  Malang: ["Blimbing", "Kedungkandang", "Klojen", "Lowokwaru", "Sukun"],
  Mojokerto: ["Magersari", "Prajurit Kulon"],
  Pasuruan: ["Bugul Kidul", "Gadingrejo", "Panggungrejo", "Purworejo"],
  Probolinggo: ["Kademangan", "Kanigaran", "Kedopok", "Mayangan", "Wonoasih"],
  Surabaya: [
    "Asemrowo",
    "Benowo",
    "Bubutan",
    "Bulak",
    "Dukuh Pakis",
    "Gayungan",
    "Genteng",
    "Gubeng",
    "Gunung Anyar",
    "Jambangan",
    "Karang Pilang",
    "Kenjeran",
    "Krembangan",
    "Lakar Santri",
    "Mulyorejo",
    "Pabean Cantian",
    "Pakal",
    "Rungkut",
    "Sambikerep",
    "Sawahan",
    "Semampir",
    "Simokerto",
    "Sukolilo",
    "Sukomanunggal",
    "Tambaksari",
    "Tandes",
    "Tegalsari",
    "Tenggilis Mejoyo",
    "Wiyung",
    "Wonocolo",
    "Wonokromo",
  ],
  Pontianak: [
    "Pontianak Barat",
    "Pontianak Kota",
    "Pontianak Selatan",
    "Pontianak Tenggara",
    "Pontianak Timur",
    "Pontianak Utara",
  ],
  Singkawang: [
    "Singkawang Barat",
    "Singkawang Selatan",
    "Singkawang Tengah",
    "Singkawang Timur",
    "Singkawang Utara",
  ],
  Banjarbaru: [
    "Banjarbaru Selatan",
    "Banjarbaru Utara",
    "Cempaka",
    "Landasan Ulin",
    "Liang Anggang",
  ],
  Banjarmasin: [
    "Banjarmasin Barat",
    "Banjarmasin Selatan",
    "Banjarmasin Tengah",
    "Banjarmasin Timur",
    "Banjarmasin Utara",
  ],
  "Palangka Raya": [
    "Bukit Batu",
    "Jekan Raya",
    "Pahandut",
    "Rakumpit",
    "Sebangau",
  ],
  Balikpapan: [
    "Balikpapan Barat",
    "Balikpapan Kota",
    "Balikpapan Selatan",
    "Balikpapan Tengah",
    "Balikpapan Timur",
    "Balikpapan Utara",
  ],
  Bontang: ["Bontang Barat", "Bontang Selatan", "Bontang Utara"],
  Samarinda: [
    "Loa Janan Ilir",
    "Palaran",
    "Samarinda Ilir",
    "Samarinda Kota",
    "Samarinda Seberang",
    "Samarinda Ulu",
    "Samarinda Utara",
    "Sungai Kunjang",
    "Sungai Pinang",
  ],
  Tarakan: [
    "Tarakan Barat",
    "Tarakan Tengah",
    "Tarakan Timur",
    "Tarakan Utara",
  ],
  "Pangkal Pinang": [
    "Bukit Intan",
    "Gabek",
    "Gerunggang",
    "Girimaya",
    "Pangkal Balam",
    "Rangkui",
    "Taman Sari",
  ],
  Batam: [
    "Batu Aji",
    "Batu Ampar",
    "Belakang Padang",
    "Bengkong",
    "Bulang",
    "Galang",
    "Lubuk Baja",
    "Nongsa",
    "Sagulung",
    "Sei Beduk",
    "Sekupang",
  ],
  "Tanjung Pinang": [
    "Bukit Bestari",
    "Tanjung Pinang Barat",
    "Tanjung Pinang Kota",
    "Tanjung Pinang Timur",
  ],
  "Bandar Lampung": [
    "Bumi Waras",
    "Enggal",
    "Kedamaian",
    "Kedaton",
    "Kemiling",
    "Labuhan Ratu",
    "Langkapura",
    "Panjang",
    "Rajabasa",
    "Sukabumi",
    "Sukarame",
    "Tanjung Karang Barat",
    "Tanjung Karang Pusat",
    "Tanjung Karang Timur",
    "Tanjung Senang",
    "Teluk Betung Barat",
    "Teluk Betung Selatan",
    "Teluk Betung Timur",
    "Teluk Betung Utara",
    "Way Halim",
  ],
  Metro: [
    "Metro Barat",
    "Metro Pusat",
    "Metro Selatan",
    "Metro Timur",
    "Metro Utara",
  ],
  Ambon: ["Baguala", "Leitimur Selatan", "Nusaniwe", "Sirimau", "Teluk Ambon"],
  Tual: [
    "Dullah Selatan",
    "Dullah Utara",
    "Pulau Dullah Selatan",
    "Pulau Dullah Utara",
  ],
  Ternate: [
    "Bacanal",
    "Kota Ternate Selatan",
    "Kota Ternate Tengah",
    "Kota Ternate Utara",
    "Moti",
    "Pulau Batang Dua",
    "Pulau Hiri",
    "Pulau Ternate",
  ],
  "Tidore Kepulauan": [
    "Oba",
    "Oba Selatan",
    "Oba Tengah",
    "Oba Utara",
    "Tidore",
    "Tidore Selatan",
    "Tidore Timur",
    "Tidore Utara",
  ],
  Bima: ["Asakota", "Mpunda", "Raba", "Rasanae Barat", "Rasanae Timur"],
  Mataram: [
    "Ampenan",
    "Cakranegara",
    "Mataram",
    "Sandubaya",
    "Sekarbela",
    "Selaparang",
  ],
  Kupang: [
    "Alak",
    "Kelapa Lima",
    "Kota Lama",
    "Kota Raja",
    "Maulafa",
    "Oebobo",
  ],
  Jayapura: [
    "Abepura",
    "Heram",
    "Jayapura Selatan",
    "Jayapura Utara",
    "Muara Tami",
  ],
  Sorong: [
    "Klaurung",
    "Maladumes",
    "Malaimsimsa",
    "Sorong",
    "Sorong Barat",
    "Sorong Kepulauan",
    "Sorong Kota",
    "Sorong Manoi",
    "Sorong Timur",
    "Sorong Utara",
  ],
  Dumai: [
    "Bukit Kapur",
    "Dumai Barat",
    "Dumai Kota",
    "Dumai Selatan",
    "Dumai Timur",
    "Medang Kampai",
    "Sungai Sembilan",
  ],
  Pekanbaru: [
    "Bukit Raya",
    "Lima Puluh",
    "Marpoyan Damai",
    "Payung Sekaki",
    "Pekanbaru Kota",
    "Rumbai",
    "Rumbai Pesisir",
    "Sail",
    "Senapelan",
    "Sukajadi",
    "Tampan",
    "Tenayan Raya",
  ],
  Mamuju: [
    "Kepulauan Bala Balakang",
    "Mamuju",
    "Simboro dan Kepulauan",
    "Tapalang",
    "Tapalang Barat",
  ],
  Makassar: [
    "Biringkanaya",
    "Bontoala",
    "Makassar",
    "Mamajang",
    "Manggala",
    "Mariso",
    "Panakkukang",
    "Rappocini",
    "Tallo",
    "Tamalanrea",
    "Tamalate",
    "Ujung Pandang",
    "Ujung Tanah",
    "Wajo",
  ],
  Palopo: [
    "Bara",
    "Mungkajang",
    "Sendana",
    "Telluwanua",
    "Wara",
    "Wara Barat",
    "Wara Selatan",
    "Wara Timur",
    "Wara Utara",
  ],
  Parepare: ["Bacukiki", "Bacukiki Barat", "Soreang", "Ujung"],
  Palu: [
    "Mantikulore",
    "Palu Barat",
    "Palu Selatan",
    "Palu Timur",
    "Palu Utara",
    "Tatanga",
    "Tawaeli",
    "Ulujadi",
  ],
  "Bau-Bau": [
    "Betoambari",
    "Bungi",
    "Kokalukuna",
    "Lea-Lea",
    "Murhum",
    "Sorawolio",
    "Wolio",
  ],
  Kendari: [
    "Abeli",
    "Baruga",
    "Kadia",
    "Kambu",
    "Kendari",
    "Kendari Barat",
    "Mandonga",
    "Poasia",
    "Puuwatu",
    "Wua-Wua",
  ],
  Bitung: [
    "Aertembaga",
    "Girian",
    "Lembeh Selatan",
    "Lembeh Utara",
    "Madidir",
    "Maesa",
    "Matuari",
    "Ranowulu",
  ],
  Kotamobagu: [
    "Kotamobagu Barat",
    "Kotamobagu Selatan",
    "Kotamobagu Timur",
    "Kotamobagu Utara",
  ],
  Manado: [
    "Bunaken",
    "Bunaken Kepulauan",
    "Malalayang",
    "Mapanget",
    "Paal Dua",
    "Sario",
    "Singkil",
    "Tikala",
    "Tuminting",
    "Wanea",
    "Wenang",
  ],
  Tomohon: [
    "Tomohon Barat",
    "Tomohon Selatan",
    "Tomohon Tengah",
    "Tomohon Timur",
    "Tomohon Utara",
  ],
  Bukittinggi: [
    "Aur Birugo Tigo Baleh",
    "Guguk Panjang",
    "Mandiangin Koto Selayan",
  ],
  Padang: [
    "Bungus Teluk Kabung",
    "Koto Tangah",
    "Kuranji",
    "Lubuk Begalung",
    "Lubuk Kilangan",
    "Nanggalo",
    "Padang Barat",
    "Padang Selatan",
    "Padang Timur",
    "Padang Utara",
    "Pauh",
  ],
  "Padang Panjang": ["Padang Panjang Barat", "Padang Panjang Timur"],
  Pariaman: [
    "Pariaman Selatan",
    "Pariaman Tengah",
    "Pariaman Timur",
    "Pariaman Utara",
  ],
  Payakumbuh: [
    "Lamposi Tigo Nagori",
    "Payakumbuh Barat",
    "Payakumbuh Selatan",
    "Payakumbuh Timur",
    "Payakumbuh Utara",
  ],
  Sawahlunto: ["Barangin", "Lembah Segar", "Silungkang", "Talawi"],
  Solok: ["Lubuk Sikarah", "Tanjung Harapan"],
  Lubuklinggau: [
    "Lubuklinggau Barat I",
    "Lubuklinggau Barat II",
    "Lubuklinggau Selatan I",
    "Lubuklinggau Selatan II",
    "Lubuklinggau Timur I",
    "Lubuklinggau Timur II",
    "Lubuklinggau Utara I",
    "Lubuklinggau Utara II",
  ],
  "Pagar Alam": [
    "Dempo Selatan",
    "Dempo Tengah",
    "Dempo Utara",
    "Pagar Alam Selatan",
    "Pagar Alam Utara",
  ],
  Palembang: [
    "Alang-Alang Lebar",
    "Bukit Kecil",
    "Gandus",
    "Ilir Barat I",
    "Ilir Barat II",
    "Ilir Timur I",
    "Ilir Timur II",
    "Kalidoni",
    "Kemuning",
    "Kertapati",
    "Plaju",
    "Sako",
    "Seberang Ulu I",
    "Seberang Ulu II",
    "Sematang Borang",
    "Sukarami",
  ],
  Prabumulih: [
    "Cambai",
    "Prabumulih Barat",
    "Prabumulih Selatan",
    "Prabumulih Timur",
    "Prabumulih Utara",
    "Rambang Kapak Tengah",
  ],
  Binjai: [
    "Binjai Barat",
    "Binjai Kota",
    "Binjai Selatan",
    "Binjai Timur",
    "Binjai Utara",
  ],
  Gunungsitoli: [
    "Gunungsitoli",
    "Gunungsitoli Alo'oa",
    "Gunungsitoli Barat",
    "Gunungsitoli Idanoi",
    "Gunungsitoli Selatan",
    "Gunungsitoli Utara",
  ],
  Medan: [
    "Medan Amplas",
    "Medan Area",
    "Medan Barat",
    "Medan Baru",
    "Medan Belawan",
    "Medan Deli",
    "Medan Denai",
    "Medan Helvetia",
    "Medan Johor",
    "Medan Kota",
    "Medan Labuhan",
    "Medan Maimun",
    "Medan Marelan",
    "Medan Perjuangan",
    "Medan Petisah",
    "Medan Polonia",
    "Medan Selayang",
    "Medan Sunggal",
    "Medan Tembung",
    "Medan Timur",
    "Medan Tuntungan",
  ],

  "Padang Sidempuan": [
    "Padang Sidempuan Angkola Julu",
    "Padang Sidempuan Batunadua",
    "Padang Sidempuan Hutaimbaru",
    "Padang Sidempuan Selatan",
    "Padang Sidempuan Tenggara",
    "Padang Sidempuan Utara",
  ],
  Pematangsiantar: [
    "Siantar Barat",
    "Siantar Marihat",
    "Siantar Marimbun",
    "Siantar Martoba",
    "Siantar Selatan",
    "Siantar Sitalasari",
    "Siantar Timur",
    "Siantar Utara",
  ],
  Sibolga: [
    "Sibolga Kota",
    "Sibolga Sambas",
    "Sibolga Selatan",
    "Sibolga Utara",
  ],
  Tanjungbalai: [
    "Datuk Bandar",
    "Datuk Bandar Timur",
    "Sei Tualang Raso",
    "Tanjung Balai Selatan",
    "Tanjung Balai Utara",
    "Teluk Nibung",
  ],
  "Tebing Tinggi": [
    "Bajenis",
    "Padang Hilir",
    "Padang Hulu",
    "Rambutan",
    "Tebing Tinggi Kota",
  ],
};

export function getCitiesByProvince(province: string): string[] {
  return citiesByProvince[province] || [];
}

export function getDistrictsByCity(city: string): string[] {
  return districtsByCity[city] || [];
}
